#!/usr/bin/env python3
from pathlib import Path
import json
import subprocess
import sys

ROOT = Path(__file__).resolve().parents[1]

subprocess.run([sys.executable, str(ROOT / "workers" / "self_improve.py")], check=True)

score = json.loads((ROOT / "state" / "HARNESS_SCORECARD.json").read_text())
assert score["incident_count"] >= 1, score
assert score["learned_rule_count"] >= 1, score
assert score["wins"] + score["losses"] + score["blocked"] + score["open"] >= 1, score

win_loss = (ROOT / "state" / "WIN_LOSS_ANALYSIS.md").read_text()
rules = (ROOT / "state" / "AUTOGENERATED_RULES.md").read_text()
weird = (ROOT / "state" / "WEIRD_SALVAGE_INDEX.md").read_text()

assert "Win / Loss Analysis" in win_loss
assert "Auto-Generated Learned Rules" in rules
assert "No learned rules yet." not in rules
assert "Weird Salvage Index" in weird
print("Harness self-improvement worker PASS")
