#!/usr/bin/env python3
from pathlib import Path
import json, subprocess, sys
ROOT=Path(__file__).resolve().parents[1]
subprocess.run([sys.executable,str(ROOT/"workers"/"self_improve.py")],check=True)
score=json.loads((ROOT/"state"/"HARNESS_SCORECARD.json").read_text())
assert score["incident_count"]>=1
assert score["learned_rule_count"]>=1
assert "Win / Loss Analysis" in (ROOT/"state"/"WIN_LOSS_ANALYSIS.md").read_text()
assert "Auto-Generated Learned Rules" in (ROOT/"state"/"AUTOGENERATED_RULES.md").read_text()
assert "Weird Salvage Index" in (ROOT/"state"/"WEIRD_SALVAGE_INDEX.md").read_text()
print("Harness self-improvement worker PASS")
