#!/usr/bin/env python3
from pathlib import Path
import json
import subprocess
import sys

ROOT = Path(__file__).resolve().parents[1]
subprocess.run([sys.executable, str(ROOT / "workers" / "self_improve.py")], check=True)
subprocess.run([sys.executable, str(ROOT / "workers" / "learning_intake.py")], check=True)

index = (ROOT / "state" / "LEARNING_CANDIDATE_INDEX.md").read_text(encoding="utf-8")
rules = (ROOT / "state" / "AUTOGENERATED_RULES.md").read_text(encoding="utf-8")
score = json.loads((ROOT / "state" / "HARNESS_SCORECARD.json").read_text(encoding="utf-8"))

assert "LC-2026-10-04-CONSTRAINT-INVERSION" in index
assert "Raw private chat is not an input" in index
assert "Proven generalized learning candidates" in rules
assert "No proven generalized learning candidates yet." in rules
assert score["learning_candidate_count"] >= 1, score
assert score["proven_learning_candidate_count"] == 0, score
print("FRIDAY learning intake PASS")
