#!/usr/bin/env python3
"""Render continuity from CURRENT_PROJECT; observe remote refs without promoting them."""
from __future__ import annotations

import argparse
from datetime import datetime, timezone
import hashlib
import json
import os
from pathlib import Path
import re
import sys
from urllib.error import HTTPError, URLError
from urllib.parse import quote
from urllib.request import Request, urlopen

ROOT = Path(__file__).resolve().parents[1]
ROLE_KEYS = {
    "governance": ("repo", "branch"),
    "factory": ("repo", "branch", "sha"),
    "runtime": ("repo", "branch", "sha"),
    "salvage": ("repo", "branch", "sha"),
    "cockpit": ("repo", "branch", "sha"),
}


def load(path):
    return json.loads(path.read_text(encoding="utf-8"))


def encode(data):
    return json.dumps(data, indent=2, ensure_ascii=False) + "\n"


def authority_digest(current):
    return hashlib.sha256(json.dumps(current["authority"], sort_keys=True).encode()).hexdigest()


def canonical_refs(current):
    return [{"role": role, **{
        "ref" if key == "branch" else key: current["authority"][role][key]
        for key in keys
    }} for role, keys in ROLE_KEYS.items()]


def active_order(current):
    work = current["work_order"]
    return {
        "schema_version": "1.1.0",
        "source_project_state_path": "state/CURRENT_PROJECT.json",
        **{k: current[k] for k in ("active_project", "lane", "evidence_state", "next_action")},
        **{k: work[k] for k in ("status", "blockers", "stop_condition", "gate_id")},
        "updated_at": current["last_verified_at"],
    }


def render(current):
    work = current["work_order"]
    lines = ["# Active Work Order", "",
             "> Generated by `python scripts/foundation_state.py sync`. Edit CURRENT_PROJECT.json, not this file.", "",
             f"Project: `{current['active_project']}`",
             "State source: `state/CURRENT_PROJECT.json`", "",
             f"Status: **{work['status']}** | Evidence: **{current['evidence_state']}**",
             f"Lane: {current['lane']}", "",
             "## One next gate", "", f"`{work['gate_id']}`", "", current["next_action"], "",
             "## Human path", "", work["human_path"], "",
             "## Approved component refs", "",
             "| Role | Repository | Branch | Approved commit |",
             "|---|---|---|---|"]
    for role, ref in current["authority"].items():
        lines.append(f"| {role} | {ref['repo']} | {ref['branch']} | {ref.get('sha', 'governance branch')} |")
    lines += ["", "Branch advancement is observation, not automatic promotion.", "",
              "## Known evidence", ""]
    lines += [f"- {item}" for item in work["verified_facts"]]
    lines += ["", "## Remaining gaps", ""] + [f"- {item}" for item in work["blockers"]]
    lines += ["", "## Stop condition", "", work["stop_condition"], "",
              "## Parked work (not prerequisites)", ""]
    lines += [f"- {item}" for item in work["parked"]]
    lines += ["", "## Constraints", ""] + [f"- {item}" for item in work["constraints"]]
    return "\n".join(lines) + "\n"


def resume_prompt(current):
    return ("# Foundation V0 — Current Work/Build Prompt\n\n"
            "> Generated from state/CURRENT_PROJECT.json. Historical activation maps are context only.\n\n"
            "Read AGENTS.md, OPERATING_CONTRACT.md and state/AUTOGENERATED_RULES.md.\n"
            "Run `python scripts/check_authority_spine.py`, then `python scripts/foundation_state.py status`.\n"
            "Stop on disagreement; repair it without inventing proof. Inspect live refs before editing.\n"
            "Use `python scripts/foundation_state.py observe` to detect advancement or unavailable evidence.\n"
            "Observations never change approved refs. Resume the single gate below; do not restart proven components.\n\n"
            + render(current))


def projections(root, current):
    ecosystem = load(root / "state/ECOSYSTEM_AUTHORITY_INDEX.json")
    foundation = ecosystem["active_foundation_v0"]
    foundation["canonical_refs"] = canonical_refs(current)
    foundation["next"] = current["next_action"]
    foundation["status"] = current["work_order"]["status"]
    return {
        "state/ACTIVE_WORK_ORDER.json": encode(active_order(current)),
        "state/ACTIVE_WORK_ORDER.md": render(current),
        "docs/FOUNDATION_V0_CURRENT_WORK_PROMPT.md": resume_prompt(current),
        "state/ECOSYSTEM_AUTHORITY_INDEX.json": encode(ecosystem),
    }


def contract_errors(root, current):
    errors = []
    if current.get("evidence_state") not in load(root / "config/harness.json")["evidence_states"]:
        errors.append("CURRENT_PROJECT evidence_state is not in config/harness.json")
    for role, keys in ROLE_KEYS.items():
        ref = current.get("authority", {}).get(role, {})
        for key in keys:
            if not isinstance(ref.get(key), str) or not ref[key]:
                errors.append(f"missing authority {role}.{key}")
        if "sha" in keys and not re.fullmatch(r"[0-9a-f]{40}", ref.get("sha", "")):
            errors.append(f"authority {role}.sha must be immutable full SHA")
        if not re.fullmatch(r"[A-Za-z0-9_.-]+/[A-Za-z0-9_.-]+", ref.get("repo", "")):
            errors.append(f"invalid repository for {role}")
    work = current.get("work_order", {})
    for key in ("gate_id", "status", "human_path", "stop_condition"):
        if not isinstance(work.get(key), str) or not work[key].strip():
            errors.append(f"work_order.{key} must name one explicit continuation")
    for key in ("blockers", "verified_facts", "parked", "constraints"):
        if not isinstance(work.get(key), list) or not all(isinstance(x, str) for x in work[key]):
            errors.append(f"work_order.{key} must be a list of strings")
    return errors


def projection_errors(root, current):
    errors = contract_errors(root, current)
    if errors:
        return errors
    for path, expected in projections(root, current).items():
        target = root / path
        if not target.exists() or target.read_text(encoding="utf-8") != expected:
            errors.append(f"{path} is stale; run python scripts/foundation_state.py sync")
    return errors


def github_get(path):
    headers = {"Accept": "application/vnd.github+json", "User-Agent": "Harness-read-only-observer"}
    token = os.environ.get("GH_TOKEN") or os.environ.get("GITHUB_TOKEN")
    if token:
        headers["Authorization"] = f"Bearer {token}"
    request = Request("https://api.github.com/repos/" + path, headers=headers)
    with urlopen(request, timeout=15) as response:
        return json.load(response)


def observe(current, get=github_get):
    """Read-only report. A missing credential is UNKNOWN, never a deleted repo."""
    rows = []
    for role, ref in current["authority"].items():
        row = {"role": role, "repo": ref["repo"], "branch": ref["branch"],
               "approved_sha": ref.get("sha"), "observed_sha": None}
        try:
            head = get(f"{ref['repo']}/branches/{quote(ref['branch'], safe='')}")["commit"]["sha"]
            if not re.fullmatch(r"[0-9a-f]{40}", head):
                raise ValueError("invalid branch response")
            row["observed_sha"] = head
            if ref.get("sha"):
                pinned = get(f"{ref['repo']}/commits/{ref['sha']}")["sha"]
                if pinned != ref["sha"]:
                    raise ValueError("approved commit response mismatch")
                row["state"] = "MATCH" if head == ref["sha"] else "RECONCILIATION_REQUIRED"
            else:
                row["state"] = "OBSERVED_GOVERNANCE"
        except HTTPError as exc:
            row.update(state="UNKNOWN", reason=f"HTTP_{exc.code}: existence/access unverified")
        except (URLError, TimeoutError, OSError, KeyError, TypeError, ValueError):
            row.update(state="UNKNOWN", reason="Remote evidence unavailable or malformed")
        rows.append(row)
    return {"schema_version": "1.0.0", "observed_at": datetime.now(timezone.utc).isoformat(),
            "authority_digest": authority_digest(current), "authority_changed": False,
            "scope": "BRANCH_AND_PIN_EXISTENCE_ONLY_NOT_RUNTIME_OR_DEPLOY_PROOF", "components": rows}


def main():
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("command", choices=("status", "sync", "check", "observe"))
    args = parser.parse_args()
    try:
        current = load(ROOT / "state/CURRENT_PROJECT.json")
        errors = contract_errors(ROOT, current)
        if errors:
            raise ValueError("; ".join(errors))
        if args.command == "sync":
            for path, content in projections(ROOT, current).items():
                (ROOT / path).write_text(content, encoding="utf-8")
            print("Updated derived continuity files; approved refs were not changed.")
            return 0
        errors = projection_errors(ROOT, current)
        if errors:
            raise ValueError("; ".join(errors))
        if args.command == "observe":
            report = observe(current)
            print(encode(report), end="")
            return 1 if any(r["state"] in ("UNKNOWN", "RECONCILIATION_REQUIRED") for r in report["components"]) else 0
        if args.command == "status":
            print(render(current), end="")
            print("Live refs/deployment NOT checked by status; run observe for current branch evidence.")
        else:
            print("CONTINUITY: PASS")
        return 0
    except (OSError, ValueError, KeyError, TypeError) as exc:
        print(f"CONTINUITY: BLOCKED: {exc}", file=sys.stderr)
        return 2


if __name__ == "__main__":
    raise SystemExit(main())
