#!/usr/bin/env python3
"""Validate generalized learning candidates and promote only proven rules.

This worker intentionally does not ingest raw chat. Inputs must already be generalized,
non-sensitive durable candidates in state/LEARNING_CANDIDATES.json.
"""
from __future__ import annotations

import json
from pathlib import Path

ROOT = Path(__file__).resolve().parents[1]
STATE = ROOT / "state"
SOURCE = STATE / "LEARNING_CANDIDATES.json"
RULES = STATE / "AUTOGENERATED_RULES.md"
INDEX = STATE / "LEARNING_CANDIDATE_INDEX.md"
SCORE = STATE / "HARNESS_SCORECARD.json"
ALLOWED = {"CANDIDATE", "PROVEN", "REJECTED", "RETIRED"}
START = "<!-- FRIDAY_LEARNING_CANDIDATES_START -->"
END = "<!-- FRIDAY_LEARNING_CANDIDATES_END -->"


def load_candidates() -> list[dict]:
    payload = json.loads(SOURCE.read_text(encoding="utf-8"))
    if payload.get("privacy") != "GENERALIZED_NON_SENSITIVE_ONLY":
        raise RuntimeError("learning inbox privacy marker is missing or unsafe")
    rows = payload.get("candidates")
    if not isinstance(rows, list):
        raise RuntimeError("learning candidates must be a list")
    seen = set()
    for row in rows:
        if not isinstance(row, dict):
            raise RuntimeError("learning candidate must be an object")
        for key in ("id", "status", "source", "rule", "proof"):
            if not isinstance(row.get(key), str) or not row[key].strip():
                raise RuntimeError(f"learning candidate missing {key}")
        if row["id"] in seen:
            raise RuntimeError(f"duplicate learning candidate id {row['id']}")
        seen.add(row["id"])
        if row["status"] not in ALLOWED:
            raise RuntimeError(f"invalid learning status {row['status']}")
        if row["status"] == "PROVEN" and row["proof"].upper().startswith("PENDING"):
            raise RuntimeError(f"PROVEN learning candidate has pending proof: {row['id']}")
    return rows


def render_index(rows: list[dict]) -> str:
    lines = [
        "# Learning Candidate Index",
        "",
        "> AUTO-GENERATED from sanitized generalized learning candidates. Raw private chat is not an input.",
        "",
    ]
    if not rows:
        lines.append("- No learning candidates recorded.")
    for row in rows:
        lines += [
            f"## {row['id']} — {row['status']}",
            "",
            f"- **Source:** {row['source']}",
            f"- **Rule candidate:** {row['rule']}",
            f"- **Proof:** {row['proof']}",
            f"- **Route:** {row.get('route', 'UNSPECIFIED')}",
            "",
        ]
    return "\n".join(lines) + "\n"


def render_proven(rows: list[dict]) -> str:
    proven = [row for row in rows if row["status"] == "PROVEN"]
    lines = [START, "", "## Proven generalized learning candidates", ""]
    if not proven:
        lines.append("- No proven generalized learning candidates yet.")
    for row in proven:
        lines += [
            f"### {row['id']}",
            f"- **Source:** {row['source']}",
            f"- **Rule:** {row['rule']}",
            f"- **Evidence:** {row['proof']}",
            "",
        ]
    lines.append(END)
    return "\n".join(lines)


def replace_section(text: str, section: str) -> str:
    if START in text and END in text:
        before = text.split(START, 1)[0].rstrip()
        after = text.split(END, 1)[1].lstrip()
        pieces = [before, section]
        if after:
            pieces.append(after)
        return "\n\n".join(pieces).rstrip() + "\n"
    return text.rstrip() + "\n\n" + section.rstrip() + "\n"


def main() -> None:
    rows = load_candidates()
    INDEX.write_text(render_index(rows), encoding="utf-8")

    rules = RULES.read_text(encoding="utf-8")
    RULES.write_text(replace_section(rules, render_proven(rows)), encoding="utf-8")

    score = json.loads(SCORE.read_text(encoding="utf-8"))
    score["learning_candidate_count"] = len(rows)
    score["proven_learning_candidate_count"] = sum(row["status"] == "PROVEN" for row in rows)
    SCORE.write_text(json.dumps(score, indent=2) + "\n", encoding="utf-8")
    print("Sanitized learning intake PASS")


if __name__ == "__main__":
    main()
